### ISSUE TITLE
Which Hardware/sensors will be used?

### ISSUE THREAD

**Issue by realthargor** [mvrueden/wetterkuh#1]
On which hardware/sensors will this project be build on?

**Comment by mvrueden** [comment]
There are multiple components of the project.
The plan is to have a _weather station (outdoor)_, some indoor sensors and a base station.
In the future other sensors may be added.

# Weather Station (Outdoor)
The weather station in the first iteration will collect environment information, such as:
- temperature (BME280 and DS18B20) 
- light level (BH1750)
- raining yes or no (some cheap china stuff)
- humidity (BME280)
- air pressure (BME280)
- pm2,5 and pm10 (feinstaub, SDS011)

The first prototype is probably based on an Arduino Nano (5V), but I am having some problems to get the  or NodeMCU v3 (3,3V). 

The plan is to also send data via 433,92 MHZ to the base station

# Sensors (Indoor)
Some smaller version of the Arduino Nano, don't know which one yet, but for prototyping Arduino Nano. Sensors will be BME280 or DS18B20 for environment, as not much is needed. Maybe some light sensor, either BH1750 or a simpler, analogue one. At least one indoor sensor needs some CO2 sensor, haven't looked for one yet though.
Will alos send data via 433,92MHZ to the base station.

# Base Station
The base station is receiving the raw sensor data and will put it on a MQTT broker.
A consumer will send the data to various weather endpoints.
The plan is to also have some InfluxDB and Grafana running where the received data is also stored and Grafana can be used to query and visualize the data over time very nicely.

This will probably run on a Raspberry PI Zero, with a 433,92MHZ receiver and Wifi access.
It will also run the MQTT Broker in order to encounter for internet connectivity loss. 
It will probably also get some kind of battery power supply in case a power outage occurred.

# Afterwards
After the initial prototype it is planned to get all sensors to run on battery and the weather station (outdoor) to also use solar panels to run "forever".

In addition the amount of rain and wind speed/direction is not measured yet, which would be nice to also do. If building these sensors by hand (which is very simple) or buying existing ones and hack them I don't know yet.

It is also planned to add documentation, so you don't have to ask about the details (-:
